In [3]:
#Accidentalidad Madrid part 1

In [4]:
import pandas as pd
import numpy as np

## Taking a look to the Dataset

In [5]:
df = pd.read_csv('2020_Accidentalidad.csv',sep=";")
test = pd.read_csv('2021_Accidentalidad.csv',sep=";")
df.shape

(32433, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32433 entries, 0 to 32432
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   num_expediente        32433 non-null  object
 1   fecha                 32433 non-null  object
 2   hora                  32433 non-null  object
 3   localizacion          32433 non-null  object
 4   numero                32431 non-null  object
 5   cod_distrito          32431 non-null  float64
 6   distrito              32431 non-null  object
 7   tipo_accidente        32433 non-null  object
 8   estado_meteorológico  29237 non-null  object
 9   tipo_vehiculo         32296 non-null  object
 10  tipo_persona          32433 non-null  object
 11  rango_edad            32433 non-null  object
 12  sexo                  32433 non-null  object
 13  cod_lesividad         17631 non-null  float64
 14  lesividad             17631 non-null  object
 15  coordenada_x_utm      32431 non-null  object
 16  coordenada_y_utm      32431 non-null  object
 17  positiva_alcohol      32331 non-null  object
 18  positiva_droga        82 non-null     float64
dtypes: float64(3), object(16)
memory usage: 4.7+ MB

In [7]:
df.head()

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2019S040008,07/09/2020,23:00:00,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,NaN
1,2019S040008,07/09/2020,23:00:00,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,VMU eléctrico,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,NaN
2,2020S000001,01/01/2020,1:15:00,AVDA. CANILLEJAS A VICALVARO / CALL. SILFIDE,1,20.0,SAN BLAS-CANILLEJAS,Colisión fronto-lateral,NaN,Turismo,Conductor,De 18 a 20 años,Hombre,NaN,NaN,"447894,521","4476691,236",N,NaN
3,2020S000001,01/01/2020,1:15:00,AVDA. CANILLEJAS A VICALVARO / CALL. SILFIDE,1,20.0,SAN BLAS-CANILLEJAS,Colisión fronto-lateral,NaN,Turismo,Conductor,De 30 a 34 años,Hombre,NaN,NaN,"447894,521","4476691,236",S,NaN
4,2020S000002,01/01/2020,1:20:00,"CALL. SILVANO, 31",31,16.0,HORTALEZA,Choque contra obstáculo fijo,Despejado,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"445094,901","4478370,057",N,NaN

In [8]:
# Now we create a new column extracting the number of implicates in the accident (times num_expediente is repeated)
aux=df.groupby('num_expediente').count().rename(columns={'fecha': "num_implicados"})['num_implicados']
df = pd.merge(df, aux, on='num_expediente')
# We do the same for test
aux_test=test.groupby('num_expediente').count().rename(columns={'fecha': "num_implicados"})['num_implicados']
test = pd.merge(test, aux_test, on='num_expediente')
df

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga,num_implicados
0,2019S040008,07/09/2020,23:00:00,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,NaN,2
1,2019S040008,07/09/2020,23:00:00,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,VMU eléctrico,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,NaN,2
2,2020S000001,01/01/2020,1:15:00,AVDA. CANILLEJAS A VICALVARO / CALL. SILFIDE,1,20.0,SAN BLAS-CANILLEJAS,Colisión fronto-lateral,NaN,Turismo,Conductor,De 18 a 20 años,Hombre,NaN,NaN,"447894,521","4476691,236",N,NaN,2
3,2020S000001,01/01/2020,1:15:00,AVDA. CANILLEJAS A VICALVARO / CALL. SILFIDE,1,20.0,SAN BLAS-CANILLEJAS,Colisión fronto-lateral,NaN,Turismo,Conductor,De 30 a 34 años,Hombre,NaN,NaN,"447894,521","4476691,236",S,NaN,2
4,2020S000002,01/01/2020,1:20:00,"CALL. SILVANO, 31",31,16.0,HORTALEZA,Choque contra obstáculo fijo,Despejado,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"445094,901","4478370,057",N,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32428,2020S019624,14/12/2020,11:30:00,"CALL. JOSE ARCONES GIL, 17",17,15.0,CIUDAD LINEAL,Colisión lateral,Despejado,Camión rígido,Conductor,De 35 a 39 años,Hombre,NaN,NaN,"445840,562","4476212,027",N,NaN,2
32429,2020S019624,14/12/2020,11:30:00,"CALL. JOSE ARCONES GIL, 17",17,15.0,CIUDAD LINEAL,Colisión lateral,Despejado,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"445840,562","4476212,027",N,NaN,2
32430,2020S019647,18/11/2020,10:57:00,"CALL. LOPE DE HARO, 8",8,6.0,TETUÁN,Colisión fronto-lateral,Despejado,Camión rígido,Conductor,De 40 a 44 años,Hombre,NaN,NaN,NaN,NaN,N,NaN,2
32431,2020S019647,18/11/2020,10:57:00,"CALL. LOPE DE HARO, 8",8,6.0,TETUÁN,Colisión fronto-lateral,Despejado,Furgoneta,Conductor,De 45 a 49 años,Hombre,NaN,NaN,NaN,NaN,N,NaN,2
32432,2020S019648,23/11/2020,12:54:00,"CALL. FRANCISCO SILVELA, 30",30,4.0,SALAMANCA,Caída,Nublado,Motocicleta hasta 125cc,Conductor,De 30 a 34 años,Hombre,NaN,NaN,"442999,844","4475955,235",N,NaN,1

In [9]:
# Now we can drop the column 'num_expediente'
df=df.drop(['num_expediente'], axis=1)
test=test.drop(['num_expediente'], axis=1)

In [10]:
df.isnull().sum()

fecha                       0
hora                        0
localizacion                0
numero                      2
cod_distrito                2
distrito                    2
tipo_accidente              0
estado_meteorológico     3196
tipo_vehiculo             137
tipo_persona                0
rango_edad                  0
sexo                        0
cod_lesividad           14802
lesividad               14802
coordenada_x_utm            2
coordenada_y_utm            2
positiva_alcohol          102
positiva_droga          32351
num_implicados              0
dtype: int64

## Lets work the date and hour columns

In [11]:
#let's clasify the hour column into 3 groups 
# 1. high: from 7:30 to 9:30 and from 18:00 to 20:00 monday to friday
# 2. night: from 0:00 to 7:30
# 3. low: the rest

#for this, we need to know de day of the week (from the date) 
# and we need to convert the "fecha" and "hora" columns to date_time

df['fecha']= pd.to_datetime(df['fecha'])
df['hora']= pd.to_datetime(df['hora'])
test['fecha']= pd.to_datetime(test['fecha'])
test['hora']= pd.to_datetime(test['hora'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32433 entries, 0 to 32432
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fecha                 32433 non-null  datetime64[ns]
 1   hora                  32433 non-null  datetime64[ns]
 2   localizacion          32433 non-null  object
 3   numero                32431 non-null  object
 4   cod_distrito          32431 non-null  float64
 5   distrito              32431 non-null  object
 6   tipo_accidente        32433 non-null  object
 7   estado_meteorológico  29237 non-null  object
 8   tipo_vehiculo         32296 non-null  object
 9   tipo_persona          32433 non-null  object
 10  rango_edad            32433 non-null  object
 11  sexo                  32433 non-null  object
 12  cod_lesividad         17631 non-null  float64
 13  lesividad             17631 non-null  object
 14  coordenada_x_utm      32431 non-null  object
 15  coordenada_y_utm      32431 non-null  object
 16  positiva_alcohol      32331 non-null  object
 17  positiva_droga        82 non-null     float64
 18  num_implicados        32433 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(1), object(13)
memory usage: 4.9+ MB

In [12]:
# we will extract the day of the week (dow) from the date
df_dow=df["fecha"].apply(lambda fila: fila.weekday())
df.insert(2, "dow", df_dow)
test_dow=test["fecha"].apply(lambda fila: fila.weekday())
test.insert(2, "dow", test_dow)

In [13]:
#let's clasify the hour column into 3 groups 
# 1. high: from 7:30 to 9:30 and from 18:00 to 20:00 monday to friday
# 2. night: from 0:00 to 7:30
# 3. low: the rest
time_interval_df=df.apply(lambda dfr: 'high' if (dfr['dow']>=0) & (dfr['dow']<5) & ((pd.Timestamp('7:30') <= dfr['hora']) & (pd.Timestamp('9:30') > dfr['hora']) | (pd.Timestamp('18:00') <= dfr['hora'])  & (pd.Timestamp('20:00') > dfr['hora'])) else "night" if (pd.Timestamp('00:00') <= dfr['hora'])  & (pd.Timestamp('7:30') > dfr['hora']) else "low", axis=1)
df.insert(3, "time_int", time_interval_df)
time_interval_test=test.apply(lambda dfr: 'high' if (dfr['dow']>=0) & (dfr['dow']<5) & ((pd.Timestamp('7:30') <= dfr['hora']) & (pd.Timestamp('9:30') > dfr['hora']) | (pd.Timestamp('18:00') <= dfr['hora'])  & (pd.Timestamp('20:00') > dfr['hora'])) else "night" if (pd.Timestamp('00:00') <= dfr['hora'])  & (pd.Timestamp('7:30') > dfr['hora']) else "low", axis=1)
test.insert(3, "time_int", time_interval_test)

In [14]:
time_interval_df.reset_index().groupby([0]).count()

       index
0
high    5548
low    23393
night   3492

In [15]:
df

,fecha,hora,dow,time_int,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,...,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga,num_implicados
0,2020-07-09,2022-08-08 23:00:00,3,low,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,...,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,NaN,2
1,2020-07-09,2022-08-08 23:00:00,3,low,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,...,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,NaN,2
2,2020-01-01,2022-08-08 01:15:00,2,night,AVDA. CANILLEJAS A VICALVARO / CALL. SILFIDE,1,20.0,SAN BLAS-CANILLEJAS,Colisión fronto-lateral,NaN,...,Conductor,De 18 a 20 años,Hombre,NaN,NaN,"447894,521","4476691,236",N,NaN,2
3,2020-01-01,2022-08-08 01:15:00,2,night,AVDA. CANILLEJAS A VICALVARO / CALL. SILFIDE,1,20.0,SAN BLAS-CANILLEJAS,Colisión fronto-lateral,NaN,...,Conductor,De 30 a 34 años,Hombre,NaN,NaN,"447894,521","4476691,236",S,NaN,2
4,2020-01-01,2022-08-08 01:20:00,2,night,"CALL. SILVANO, 31",31,16.0,HORTALEZA,Choque contra obstáculo fijo,Despejado,...,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"445094,901","4478370,057",N,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32428,2020-12-14,2022-08-08 11:30:00,0,low,"CALL. JOSE ARCONES GIL, 17",17,15.0,CIUDAD LINEAL,Colisión lateral,Despejado,...,Conductor,De 35 a 39 años,Hombre,NaN,NaN,"445840,562","4476212,027",N,NaN,2
32429,2020-12-14,2022-08-08 11:30:00,0,low,"CALL. JOSE ARCONES GIL, 17",17,15.0,CIUDAD LINEAL,Colisión lateral,Despejado,...,Conductor,Desconocido,Desconocido,NaN,NaN,"445840,562","4476212,027",N,NaN,2
32430,2020-11-18,2022-08-08 10:57:00,2,low,"CALL. LOPE DE HARO, 8",8,6.0,TETUÁN,Colisión fronto-lateral,Despejado,...,Conductor,De 40 a 44 años,Hombre,NaN,NaN,NaN,NaN,N,NaN,2
32431,2020-11-18,2022-08-08 10:57:00,2,low,"CALL. LOPE DE HARO, 8",8,6.0,TETUÁN,Colisión fronto-lateral,Despejado,...,Conductor,De 45 a 49 años,Hombre,NaN,NaN,NaN,NaN,N,NaN,2
32432,2020-11-23,2022-08-08 12:54:00,0,low,"CALL. FRANCISCO SILVELA, 30",30,4.0,SALAMANCA,Caída,Nublado,...,Conductor,De 30 a 34 años,Hombre,NaN,NaN,"442999,844","4475955,235",N,NaN,1

## Downloading API json climate data from AEMET

#### We are going to check that the column "estado_meteorológico" that comes in the raw data, match the API information downloaded from the official weather agency in Spain AEMET

In [16]:
import requests
import json

api_key = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbXNnOTRAZ21haWwuY29tIiwianRpIjoiMTY1N2FlOWItNTExYy00Y2FjLTljMGMtNzljZTg2YjE3MjZiIiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE1ODM0OTQzNDEsInVzZXJJZCI6IjE2NTdhZTliLTUxMWMtNGNhYy05YzBjLTc5Y2U4NmIxNzI2YiIsInJvbGUiOiIifQ.TjMpJc94DbOJSZPu9nsYio3eTShJr4YNPecsLyxpIGY'

startdate= '2020-01-01T00:00:00UTC'
finishdate= '2021-12-31T00:00:00UTC'
station= '3195' #retiro station

url= 'https://opendata.aemet.es/opendata/api/valores/climatologicos/diarios/datos/fechaini/'+startdate+'/fechafin/'+finishdate+'/estacion/'+station
response = requests.get(url, params={'api_key': api_key})
response.status_code

200

In [17]:
resp_dict = json.loads(response.text)
resp_dict

{'descripcion': 'exito',
 'estado': 200,
 'datos': 'https://opendata.aemet.es/opendata/sh/2b8d58fe',
 'metadatos': 'https://opendata.aemet.es/opendata/sh/b3aa9d28'}

In [18]:
response_data = requests.get(resp_dict.get('datos'), params={'api_key': api_key})
dict_retiro_station = json.loads(response_data.text)
weather_api = pd.DataFrame(dict_retiro_station)
weather_api

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,horatmin,tmax,horatmax,dir,velmedia,racha,horaracha,presMax,horaPresMax,presMin,horaPresMin
0,2020-01-01,3195,"MADRID, RETIRO",MADRID,667,"6,6","0,0","1,9",07:50,"11,2",15:30,05,"0,3","3,3",00:50,"954,2",11,"952,0",Varias
1,2020-01-02,3195,"MADRID, RETIRO",MADRID,667,"6,0","0,0","1,6",07:00,"10,5",15:00,99,"0,6","3,3",Varias,"953,7",10,"951,0",15
2,2020-01-03,3195,"MADRID, RETIRO",MADRID,667,"3,8","0,0","1,5",06:00,"6,0",14:40,99,"0,6","5,0",Varias,"954,8",Varias,"952,2",Varias
3,2020-01-04,3195,"MADRID, RETIRO",MADRID,667,"7,0","0,0","2,8",00:20,"11,2",14:45,04,"2,5","9,4",12:00,"955,9",10,"952,5",16
4,2020-01-05,3195,"MADRID, RETIRO",MADRID,667,"6,2","0,0","1,5",08:30,"10,9",13:50,05,"0,8","5,3",00:00,"953,3",00,"949,2",16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2021-12-27,3195,"MADRID, RETIRO",MADRID,667,"12,2","0,0","10,1",Varias,"14,3",13:40,NaN,NaN,NaN,NaN,"941,5",24,"933,2",02
727,2021-12-28,3195,"MADRID, RETIRO",MADRID,667,"11,4","0,0","8,3",23:20,"14,6",13:50,NaN,NaN,NaN,NaN,"946,7",Varias,"941,2",00
728,2021-12-29,3195,"MADRID, RETIRO",MADRID,667,"9,8","0,0","7,0",03:10,"12,6",15:00,NaN,NaN,NaN,NaN,"949,0",10,"946,6",00
729,2021-12-30,3195,"MADRID, RETIRO",MADRID,667,"9,8","0,0","4,7",08:10,"14,9",15:40,NaN,NaN,NaN,NaN,"948,2",23,"945,6",15
730,2021-12-31,3195,"MADRID, RETIRO",MADRID,667,"10,2","0,0","5,0",07:30,"15,5",15:00,NaN,NaN,NaN,NaN,"951,1",10,"947,6",01

In [19]:
#The only column which we are going to pay attention to is 'prec' (rainfall). we will consider wet to be more than 0.1 mm.
weather_api['prec']=weather_api['prec'].str.replace(',','.')
weather_api['prec']=pd.to_numeric(weather_api['prec'],errors='coerce')

In [20]:
# We set the column 'fecha' as index in order to do the merge later
weather_api['fecha']= pd.to_datetime(weather_api['fecha'])
weather_api=weather_api.set_index('fecha')

In [21]:
prec=weather_api['prec']
prec

fecha
2020-01-01    0.0
2020-01-02    0.0
2020-01-03    0.0
2020-01-04    0.0
2020-01-05    0.0
             ...
2021-12-27    0.0
2021-12-28    0.0
2021-12-29    0.0
2021-12-30    0.0
2021-12-31    0.0
Name: prec, Length: 731, dtype: float64

In [22]:
print(df.shape)
print(test.shape)

(32433, 21)
(41783, 21)

In [23]:
# We merge the column "prec" to the main df and to the test 
df=df.merge(prec, left_on='fecha',right_index=True)
test=test.merge(prec, left_on='fecha',right_index=True)

In [24]:
print(df.shape)
print(test.shape)

(32433, 22)
(41783, 22)

In [25]:
df['estado_meteorológico'].unique()

array(['Despejado', nan, 'Se desconoce', 'Lluvia débil', 'Nublado',
       'LLuvia intensa', 'Granizando', 'Nevando'], dtype=object)

In [26]:
# Reminder: we will consider wet, the column 'prec' to be more than 0.1 mm
df['despejado_checked']=df.apply(lambda dfr: 1 if ((dfr['prec']<=0.1) & (dfr['estado_meteorológico']=='Despejado')) else 0, axis=1)
df['lluviad_checked']=df.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Lluvia débil')) else 0, axis=1)
df['lluviai_checked']=df.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Lluvia intensa')) else 0, axis=1)
df['nieve_checked']=df.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Nevando')) else 0, axis=1)
df['granizo_checked']=df.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Granizando')) else 0, axis=1)
df['nublado_nchecked']=df['estado_meteorológico'].apply(lambda x: 1 if x =='Nublado' else 0)
df['desconocido_nchecked']=df['estado_meteorológico'].apply(lambda x: 1 if x=='Se desconoce' else 0)

In [27]:
# Lest do the same for test
test['despejado_checked']=test.apply(lambda dfr: 1 if ((dfr['prec']<=0.1) & (dfr['estado_meteorológico']=='Despejado')) else 0, axis=1)
test['lluviad_checked']=test.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Lluvia débil')) else 0, axis=1)
test['lluviai_checked']=test.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Lluvia intensa')) else 0, axis=1)
test['nieve_checked']=test.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Nevando')) else 0, axis=1)
test['granizo_checked']=test.apply(lambda dfr: 1 if ((dfr['prec']>0.1) & (dfr['estado_meteorológico']=='Granizando')) else 0, axis=1)
test['nublado_nchecked']=test['estado_meteorológico'].apply(lambda x: 1 if x =='Nublado' else 0)
test['desconocido_nchecked']=test['estado_meteorológico'].apply(lambda x: 1 if x=='Se desconoce' else 0)

In [28]:
test

,fecha,hora,dow,time_int,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,...,positiva_droga,num_implicados,prec,despejado_checked,lluviad_checked,lluviai_checked,nieve_checked,granizo_checked,nublado_nchecked,desconocido_nchecked
0,2021-01-01,2022-08-08 04:30:00,4,night,AVDA. PABLO NERUDA / CALL. LEONESES,57,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,...,NaN,5,0.0,1,0,0,0,0,0,0
1,2021-01-01,2022-08-08 04:30:00,4,night,AVDA. PABLO NERUDA / CALL. LEONESES,57,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,...,NaN,5,0.0,1,0,0,0,0,0,0
2,2021-01-01,2022-08-08 04:30:00,4,night,AVDA. PABLO NERUDA / CALL. LEONESES,57,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,...,NaN,5,0.0,1,0,0,0,0,0,0
3,2021-01-01,2022-08-08 04:30:00,4,night,AVDA. PABLO NERUDA / CALL. LEONESES,57,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,...,NaN,5,0.0,1,0,0,0,0,0,0
4,2021-01-01,2022-08-08 04:30:00,4,night,AVDA. PABLO NERUDA / CALL. LEONESES,57,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,...,NaN,5,0.0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41752,2021-12-31,2022-08-08 14:45:00,4,low,"CALL. GUETARIA, 41",41,12.0,USERA,Caída,Se desconoce,...,NaN,1,0.0,0,0,0,0,0,0,1
41779,2021-12-31,2022-08-08 19:10:00,4,high,AVDA. ILUSTRACION / AVDA. BETANZOS,0,8.0,FUENCARRAL-EL PARDO,Alcance,Despejado,...,NaN,2,0.0,1,0,0,0,0,0,0
41780,2021-12-31,2022-08-08 19:10:00,4,high,AVDA. ILUSTRACION / AVDA. BETANZOS,0,8.0,FUENCARRAL-EL PARDO,Alcance,Despejado,...,NaN,2,0.0,1,0,0,0,0,0,0
41781,2021-12-31,2022-08-08 17:00:00,4,low,PASEO. VAGUADA / PLAZA. JUAN PABLO FORNER,9,8.0,FUENCARRAL-EL PARDO,Colisión fronto-lateral,Despejado,...,NaN,2,0.0,1,0,0,0,0,0,0
41782,2021-12-31,2022-08-08 17:00:00,4,low,PASEO. VAGUADA / PLAZA. JUAN PABLO FORNER,9,8.0,FUENCARRAL-EL PARDO,Colisión fronto-lateral,Despejado,...,NaN,2,0.0,1,0,0,0,0,0,0

In [29]:
# This code line is only for information: Contradiction between the AEMET values and the dataset weather values.
# In this check we have compared the observations in the column "estado_meteorológico"== lluvia devil and df['prec']==0
df[(df['prec']==0)&(df['estado_meteorológico']=='Lluvia débil')]

,fecha,hora,dow,time_int,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,...,positiva_droga,num_implicados,prec,despejado_checked,lluviad_checked,lluviai_checked,nieve_checked,granizo_checked,nublado_nchecked,desconocido_nchecked
130,2020-02-01,2022-08-08 17:15:00,5,low,"AVDA. PALOMERAS, 60B",60B,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0
131,2020-02-01,2022-08-08 17:15:00,5,low,"AVDA. PALOMERAS, 60B",60B,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0
2556,2020-07-01,2022-08-08 06:30:00,2,night,AVDA. MIRAFLORES / CTRA. DEHESA DE LA VILLA,2,9.0,MONCLOA-ARAVACA,Vuelco,Lluvia débil,...,NaN,1,0.0,0,0,0,0,0,0,0
739,2020-08-01,2022-08-08 17:30:00,5,low,CTRA. VILLAVERDE A VALLECAS / CMNO. POZO DEL T...,267,18.0,VILLA DE VALLECAS,Colisión lateral,Lluvia débil,...,NaN,4,0.0,0,0,0,0,0,0,0
740,2020-08-01,2022-08-08 17:30:00,5,low,CTRA. VILLAVERDE A VALLECAS / CMNO. POZO DEL T...,267,18.0,VILLA DE VALLECAS,Colisión lateral,Lluvia débil,...,NaN,4,0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31581,2020-12-24,2022-08-08 14:20:00,3,low,"CALL. PRINCESA, 98",98,9.0,MONCLOA-ARAVACA,Colisión lateral,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0
31665,2020-12-24,2022-08-08 13:30:00,3,low,"AUTOV. M-30, +01000E P.K. 10,200",+01000E,13.0,PUENTE DE VALLECAS,Alcance,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0
31666,2020-12-24,2022-08-08 13:30:00,3,low,"AUTOV. M-30, +01000E P.K. 10,200",+01000E,13.0,PUENTE DE VALLECAS,Alcance,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0
31955,2020-12-24,2022-08-08 05:50:00,3,night,CALL. PEDRO RICO / CALL. ARZOBISPO MORCILLO,1,8.0,FUENCARRAL-EL PARDO,Choque contra obstáculo fijo,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0
31956,2020-12-24,2022-08-08 05:50:00,3,night,CALL. PEDRO RICO / CALL. ARZOBISPO MORCILLO,1,8.0,FUENCARRAL-EL PARDO,Choque contra obstáculo fijo,Lluvia débil,...,NaN,2,0.0,0,0,0,0,0,0,0

## Arranging the Data

In [30]:
# We set a new column indicating with 1 if it is a crossroad and 0 if not
df['cruce']=df['localizacion'].apply(lambda x: 1 if x.find('/')!=(-1) else 0 )
test['cruce']=test['localizacion'].apply(lambda x: 1 if x.find('/')!=(-1) else 0 )

In [31]:
pd.set_option("display.max_columns", None)
df

,fecha,hora,dow,time_int,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga,num_implicados,prec,despejado_checked,lluviad_checked,lluviai_checked,nieve_checked,granizo_checked,nublado_nchecked,desconocido_nchecked,cruce
0,2020-07-09,2022-08-08 23:00:00,3,low,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,NaN,2,0.0,1,0,0,0,0,0,0,0
1,2020-07-09,2022-08-08 23:00:00,3,low,"CALL. SAN MAXIMILIANO, 38",38,15.0,CIUDAD LINEAL,Choque contra obstáculo fijo,Despejado,VMU eléctrico,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,NaN,2,0.0,1,0,0,0,0,0,0,0
19809,2020-07-09,2022-08-08 00:15:00,3,night,PLAZA. MARTINEZ DE LA RIVA / CALL. PUERTO DE A...,7,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,Camión rígido,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,NaN,2,0.0,1,0,0,0,0,0,0,1
19810,2020-07-09,2022-08-08 00:15:00,3,night,PLAZA. MARTINEZ DE LA RIVA / CALL. PUERTO DE A...,7,13.0,PUENTE DE VALLECAS,Colisión fronto-lateral,Despejado,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,NaN,2,0.0,1,0,0,0,0,0,0,1
19811,2020-07-09,2022-08-08 00:05:00,3,night,PASEO. FLORIDA / CALL. MAESTRO SOROZABAL,10,9.0,MONCLOA-ARAVACA,Choque contra obstáculo fijo,Despejado,Turismo,Conductor,De 25 a 29 años,Hombre,NaN,NaN,"438733,091","4474891,441",N,NaN,2,0.0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32399,2020-12-31,2022-08-08 19:00:00,3,high,AVDA. MACHUPICHU / PAPA,19,16.0,HORTALEZA,Choque contra obstáculo fijo,Lluvia débil,Turismo,Conductor,De 18 a 20 años,Mujer,NaN,NaN,"447030,571","4478737,664",N,NaN,3,1.0,0,1,0,0,0,0,0,1
32400,2020-12-31,2022-08-08 19:00:00,3,high,AVDA. MACHUPICHU / PAPA,19,16.0,HORTALEZA,Choque contra obstáculo fijo,Lluvia débil,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"447030,571","4478737,664",N,NaN,3,1.0,0,1,0,0,0,0,0,1
32401,2020-12-31,2022-08-08 19:00:00,3,high,AVDA. MACHUPICHU / PAPA,19,16.0,HORTALEZA,Choque contra obstáculo fijo,Lluvia débil,Turismo,Pasajero,De 18 a 20 años,Mujer,14.0,Sin asistencia sanitaria,"447030,571","4478737,664",N,NaN,3,1.0,0,1,0,0,0,0,0,1
32406,2020-12-31,2022-08-08 16:55:00,3,low,GTA. LUIS ROSALES / CALL. LOPEZ DE HOYOS,0,16.0,HORTALEZA,Colisión fronto-lateral,Lluvia débil,Turismo,Conductor,De 18 a 20 años,Mujer,2.0,Ingreso inferior o igual a 24 horas,"444576,588","4479781,905",N,NaN,2,1.0,0,1,0,0,0,0,0,1
32407,2020-12-31,2022-08-08 16:55:00,3,low,GTA. LUIS ROSALES / CALL. LOPEZ DE HOYOS,0,16.0,HORTALEZA,Colisión fronto-lateral,Lluvia débil,Turismo,Conductor,De 21 a 24 años,Hombre,14.0,Sin asistencia sanitaria,"444576,588","4479781,905",N,NaN,2,1.0,0,1,0,0,0,0,0,1

In [32]:
# Now we are going to delete some columns which we don't need anymore
df1=df.drop(['fecha','hora','localizacion','numero','cod_distrito','estado_meteorológico','prec','positiva_droga'], axis=1)
test1=test.drop(['fecha','hora','localizacion','numero','cod_distrito','estado_meteorológico','prec','positiva_droga'], axis=1)

In [33]:
print(df1.shape)
print(test1.shape)

(32433, 22)
(41783, 22)

In [34]:
df1

,dow,time_int,distrito,tipo_accidente,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,num_implicados,despejado_checked,lluviad_checked,lluviai_checked,nieve_checked,granizo_checked,nublado_nchecked,desconocido_nchecked,cruce
0,3,low,CIUDAD LINEAL,Choque contra obstáculo fijo,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,2,1,0,0,0,0,0,0,0
1,3,low,CIUDAD LINEAL,Choque contra obstáculo fijo,VMU eléctrico,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,2,1,0,0,0,0,0,0,0
19809,3,night,PUENTE DE VALLECAS,Colisión fronto-lateral,Camión rígido,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,2,1,0,0,0,0,0,0,1
19810,3,night,PUENTE DE VALLECAS,Colisión fronto-lateral,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,2,1,0,0,0,0,0,0,1
19811,3,night,MONCLOA-ARAVACA,Choque contra obstáculo fijo,Turismo,Conductor,De 25 a 29 años,Hombre,NaN,NaN,"438733,091","4474891,441",N,2,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32399,3,high,HORTALEZA,Choque contra obstáculo fijo,Turismo,Conductor,De 18 a 20 años,Mujer,NaN,NaN,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1
32400,3,high,HORTALEZA,Choque contra obstáculo fijo,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1
32401,3,high,HORTALEZA,Choque contra obstáculo fijo,Turismo,Pasajero,De 18 a 20 años,Mujer,14.0,Sin asistencia sanitaria,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1
32406,3,low,HORTALEZA,Colisión fronto-lateral,Turismo,Conductor,De 18 a 20 años,Mujer,2.0,Ingreso inferior o igual a 24 horas,"444576,588","4479781,905",N,2,0,1,0,0,0,0,0,1
32407,3,low,HORTALEZA,Colisión fronto-lateral,Turismo,Conductor,De 21 a 24 años,Hombre,14.0,Sin asistencia sanitaria,"444576,588","4479781,905",N,2,0,1,0,0,0,0,0,1

In [35]:
print(len(df1['tipo_vehiculo'].unique()))
df1['tipo_vehiculo'].unique()

36

array(['Turismo', 'VMU eléctrico', 'Camión rígido', 'Todo terreno',
       'Motocicleta hasta 125cc', 'Furgoneta', 'Motocicleta > 125cc',
       'Bicicleta', 'Autobús', 'Ciclomotor', 'Tractocamión',
       'Otros vehículos con motor', 'Autobús articulado', nan,
       'Maquinaria de obras', 'Autobus EMT', 'Vehículo articulado',
       'Ciclo', 'Bicicleta EPAC (pedaleo asistido)', 'Cuadriciclo ligero',
       'Otros vehículos sin motor', 'Moto de tres ruedas > 125cc',
       'Cuadriciclo no ligero', 'Sin especificar', 'Tren/metro',
       'Ambulancia SAMUR', 'Remolque', 'Autocaravana',
       'Moto de tres ruedas hasta 125cc',
       'Ciclomotor de dos ruedas L1e-B', 'Maquinaria agrícola',
       'Autobús articulado EMT', 'Camión de bomberos', 'Semiremolque',
       'Patinete', 'Ciclomotor de tres ruedas'], dtype=object)

In [36]:
# As we see in the last box, we have 26 different types of vehicle tipe. now we will see the % of each. 
aux=df1.groupby('tipo_vehiculo').count().iloc[:,0:1].sort_values(by='dow',ascending=False)
aux['%']=aux['dow']*100/aux['dow'].sum()
aux

                                     dow          %
tipo_vehiculo
Turismo                            22086  68.386178
Motocicleta hasta 125cc             2431   7.527248
Furgoneta                           2252   6.973000
Motocicleta > 125cc                 1381   4.276071
Camión rígido                        818   2.532821
Bicicleta                            802   2.483280
Autobús                              637   1.972380
Ciclomotor                           507   1.569854
Todo terreno                         429   1.328338
VMU eléctrico                        179   0.554248
Tractocamión                         159   0.492321
Bicicleta EPAC (pedaleo asistido)    127   0.393238
Otros vehículos con motor            113   0.349889
Maquinaria de obras                   75   0.232227
Autobus EMT                           66   0.204360
Autobús articulado                    53   0.164107
Vehículo articulado                   49   0.151722
Ciclo                                 29   0.089794
Sin especificar                       28   0.086698
Cuadriciclo ligero                    20   0.061927
Cuadriciclo no ligero                 13   0.040253
Moto de tres ruedas > 125cc           12   0.037156
Ambulancia SAMUR                       5   0.015482
Ciclomotor de dos ruedas L1e-B         4   0.012385
Remolque                               3   0.009289
Camión de bomberos                     3   0.009289
Autocaravana                           3   0.009289
Autobús articulado EMT                 3   0.009289
Patinete                               2   0.006193
Maquinaria agrícola                    2   0.006193
Moto de tres ruedas hasta 125cc        1   0.003096
Otros vehículos sin motor              1   0.003096
Semiremolque                           1   0.003096
Ciclomotor de tres ruedas              1   0.003096
Tren/metro                             1   0.003096

In [37]:
# 68% of the vehicles are ordinary cars, 12% are motorcycles and 8% are vans. That makes 88%. the other 32 categories, 
# correspond to the remaining 12%. So we will reorganice all vehicle-tipes into 4 categories:
# Car, Van, Motorcycle and Others
df1['grupo_vehi']=df1['tipo_vehiculo'].apply(lambda x: 'turismo' if x=='Turismo' else 'furgoneta' if x=='Furgoneta' else 'ciclomotor' if (x=='Motocicleta hasta 125cc')|(x=='Motocicleta > 125cc') else 'resto')

# And we do the same for test 
test1['grupo_vehi']=test1['tipo_vehiculo'].apply(lambda x: 'turismo' if x=='Turismo' else 'furgoneta' if x=='Furgoneta' else 'ciclomotor' if (x=='Motocicleta hasta 125cc')|(x=='Motocicleta > 125cc') else 'resto')

In [38]:
df1

,dow,time_int,distrito,tipo_accidente,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,num_implicados,despejado_checked,lluviad_checked,lluviai_checked,nieve_checked,granizo_checked,nublado_nchecked,desconocido_nchecked,cruce,grupo_vehi
0,3,low,CIUDAD LINEAL,Choque contra obstáculo fijo,Turismo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,2,1,0,0,0,0,0,0,0,turismo
1,3,low,CIUDAD LINEAL,Choque contra obstáculo fijo,VMU eléctrico,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,2,1,0,0,0,0,0,0,0,resto
19809,3,night,PUENTE DE VALLECAS,Colisión fronto-lateral,Camión rígido,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,2,1,0,0,0,0,0,0,1,resto
19810,3,night,PUENTE DE VALLECAS,Colisión fronto-lateral,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,2,1,0,0,0,0,0,0,1,turismo
19811,3,night,MONCLOA-ARAVACA,Choque contra obstáculo fijo,Turismo,Conductor,De 25 a 29 años,Hombre,NaN,NaN,"438733,091","4474891,441",N,2,1,0,0,0,0,0,0,1,turismo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32399,3,high,HORTALEZA,Choque contra obstáculo fijo,Turismo,Conductor,De 18 a 20 años,Mujer,NaN,NaN,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1,turismo
32400,3,high,HORTALEZA,Choque contra obstáculo fijo,Turismo,Conductor,Desconocido,Desconocido,NaN,NaN,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1,turismo
32401,3,high,HORTALEZA,Choque contra obstáculo fijo,Turismo,Pasajero,De 18 a 20 años,Mujer,14.0,Sin asistencia sanitaria,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1,turismo
32406,3,low,HORTALEZA,Colisión fronto-lateral,Turismo,Conductor,De 18 a 20 años,Mujer,2.0,Ingreso inferior o igual a 24 horas,"444576,588","4479781,905",N,2,0,1,0,0,0,0,0,1,turismo
32407,3,low,HORTALEZA,Colisión fronto-lateral,Turismo,Conductor,De 21 a 24 años,Hombre,14.0,Sin asistencia sanitaria,"444576,588","4479781,905",N,2,0,1,0,0,0,0,0,1,turismo

In [39]:
# Now we will do the one_hot encoding for 'grupo_vehi' and remove the columns regarding to vehicles ('grupo_vehi' & 'tipo_vehiculo)
aux=pd.get_dummies(df1[['grupo_vehi']],columns=['grupo_vehi'],prefix='vehi_')
df2=pd.concat([df1,aux],axis=1)
df2=df2.drop(['grupo_vehi','tipo_vehiculo'], axis=1)

# Now we will do the same for test
aux_test=pd.get_dummies(test1[['grupo_vehi']],columns=['grupo_vehi'],prefix='vehi_')
test2=pd.concat([test1,aux_test],axis=1)
test2=test2.drop(['grupo_vehi','tipo_vehiculo'], axis=1)
df2

,dow,time_int,distrito,tipo_accidente,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,num_implicados,despejado_checked,lluviad_checked,lluviai_checked,nieve_checked,granizo_checked,nublado_nchecked,desconocido_nchecked,cruce,vehi__ciclomotor,vehi__furgoneta,vehi__resto,vehi__turismo
0,3,low,CIUDAD LINEAL,Choque contra obstáculo fijo,Conductor,De 21 a 24 años,Hombre,NaN,NaN,"444578,153","4475148,102",N,2,1,0,0,0,0,0,0,0,0,0,0,1
1,3,low,CIUDAD LINEAL,Choque contra obstáculo fijo,Conductor,De 25 a 29 años,Mujer,NaN,NaN,"444578,153","4475148,102",N,2,1,0,0,0,0,0,0,0,0,0,1,0
19809,3,night,PUENTE DE VALLECAS,Colisión fronto-lateral,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,2,1,0,0,0,0,0,0,1,0,0,1,0
19810,3,night,PUENTE DE VALLECAS,Colisión fronto-lateral,Conductor,Desconocido,Desconocido,NaN,NaN,"443600,273","4471136,444",N,2,1,0,0,0,0,0,0,1,0,0,0,1
19811,3,night,MONCLOA-ARAVACA,Choque contra obstáculo fijo,Conductor,De 25 a 29 años,Hombre,NaN,NaN,"438733,091","4474891,441",N,2,1,0,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32399,3,high,HORTALEZA,Choque contra obstáculo fijo,Conductor,De 18 a 20 años,Mujer,NaN,NaN,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1,0,0,0,1
32400,3,high,HORTALEZA,Choque contra obstáculo fijo,Conductor,Desconocido,Desconocido,NaN,NaN,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1,0,0,0,1
32401,3,high,HORTALEZA,Choque contra obstáculo fijo,Pasajero,De 18 a 20 años,Mujer,14.0,Sin asistencia sanitaria,"447030,571","4478737,664",N,3,0,1,0,0,0,0,0,1,0,0,0,1
32406,3,low,HORTALEZA,Colisión fronto-lateral,Conductor,De 18 a 20 años,Mujer,2.0,Ingreso inferior o igual a 24 horas,"444576,588","4479781,905",N,2,0,1,0,0,0,0,0,1,0,0,0,1
32407,3,low,HORTALEZA,Colisión fronto-lateral,Conductor,De 21 a 24 años,Hombre,14.0,Sin asistencia sanitaria,"444576,588","4479781,905",N,2,0,1,0,0,0,0,0,1,0,0,0,1

In [40]:
aux.isnull().sum()

vehi__ciclomotor    0
vehi__furgoneta     0
vehi__resto         0
vehi__turismo       0
dtype: int64

In [41]:
df2.to_csv('df_part1.csv',index=False)
test2.to_csv('test_part1.csv',index=False)